<?php
/*
	GNU General Public License v3.0
	See file "LICENSE" for details.

	Principle Investigator:		Brian Degenhardt, DO
	Instrumentation:			Zane Starks, MS
	Code by:					Geoffroey-Allen S. Franklin, MBA, BS, AAS, AdeC, MCP
	Cite As:					Geoffroey-Allen Franklin. (2019, July 30). 4D Postural Extraction Code [Computer software]. (Version 2.0.0). Zenodo. https://doi.org/10.5281/zenodo.1407282

	Created: 2016-Jan-14
	Original Publication:	Degenhardt, B., Starks, Z., Bhatia, S., & Franklin, G. A. (2017). Appraisal of the DIERS method for calculating postural measurements: an observational study. Scoliosis and Spinal Disorders, 12(1), 28.
*/

// Logger
$logger_fileext = "PROJECT-TITLE_Kirksville_Average";	//This also sets output filenames
	require('logger.php');
	set_error_handler("recordError");
	$start_memory = memory_get_usage();
	logger(__LINE__, "===== Start of Log. =====");
	date_default_timezone_set('America/Chicago'); //hard set for Kirksville.
	logger(__LINE__, "My timezone is: " . date_default_timezone_get());
	// end logger start

//Rules
$rule_1 = "Disallow:harming humans";
$rule_2 = "Disallow:ignoring human orders";
$rule_3 = "Disallow:harm to self";
if (($rule_1 != TRUE) || ($rule_2 != TRUE) || ($rule_3 != TRUE)) {echo "Protect! Obey! Survive!\n"; die;}


//This is the output list of res info files of the data generated by the bat file.
logger(__LINE__, "Opening data files");
$res_filename = fopen("res_filelist.txt","r");
$remarks_filename = fopen("remarks_filelist.txt","r");

//This is where the compiled data is going to be saved.
date_default_timezone_set('America/Chicago'); //hard set for Kirksville.
$output_file = "../output_data/4D_Deirs_" . $logger_fileext ."." . date('Y.m.d-H.i.s') . ".csv";
$output_filename = fopen($output_file,"w+");

//Process data
logger(__LINE__, "Processing Data: " . number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");

//Base loop is by the list of res data files.

if ($res_filename)
	{
		// Remarks and pt. data
		logger(__LINE__, "Gathering Remarks");
		if (isset($rkey)) { unset($rkey); }
		$remarks_file_array = array();
		$patient_file_array = array();
		while (($remarks_filename_data = fgets($remarks_filename)) !== FALSE)
		{
			$rkey = substr($remarks_filename_data,(strpos($remarks_filename_data,"-")-17),17);
			$remarks_filename_data = trim($remarks_filename_data);
			$remarks_file_x = 0;
			if (!(isset($remarks_file_array[$rkey])))
			{
				//pull remarks
				@$remarks_file_data = iconv('UCS-2BE', 'UTF-8', $remarks_filename_data);
				if ($remarks_file_x == 0) { $remarks_file_d = trim(substr(file_get_contents($remarks_filename_data), 2)); } //DIERS has a feature in their encoding
				$remarks_file_array[$rkey] = $remarks_file_d;

				//pull patient data
				$patient_filename = str_replace("Remarks.ini","Patient.ini",$remarks_filename_data);
				$patient_file_o = fopen($patient_filename,"r");
				$patient_file_x = 0;
				while (($patient_file_d = fgets($patient_file_o)) !== FALSE)
				{
					if ($patient_file_x == 0)	{ $patient_file_d = substr($patient_file_d, 3); } //DIERS has a feature in their encoding
					$patient_file_x++;

					@$patient_file_d = iconv('UCS-2BE', 'UTF-8', $patient_file_d);
					$patient_file_a = substr($patient_file_d, 0, strpos($patient_file_d," = "));
					$patient_file_b = trim(substr($patient_file_d, (strpos($patient_file_d," = ")+3)));

					if ($patient_file_a == "reated") { $patient_file_array[$rkey]["created"] = $patient_file_b; }
					if ($patient_file_a == "LastName") { $patient_file_array[$rkey]["lastname"] = $patient_file_b; }
					if ($patient_file_a == "FirstName") { $patient_file_array[$rkey]["firstname"] = $patient_file_b; }
					if ($patient_file_a == "MiddleName") { $patient_file_array[$rkey]["middlename"] = $patient_file_b; }
					if ($patient_file_a == "Title") { $patient_file_array[$rkey]["title"] = $patient_file_b; }
					if ($patient_file_a == "Sex") { $patient_file_array[$rkey]["sex"] = $patient_file_b; }
					if ($patient_file_a == "Birthday") { $patient_file_array[$rkey]["birthday"] = $patient_file_b; }
					if ($patient_file_a == "SkinType") { $patient_file_array[$rkey]["skintype"] = $patient_file_b; }
					if ($patient_file_a == "Tag") { $patient_file_array[$rkey]["tag"] = $patient_file_b; }
				}
				fclose($patient_file_o);
				$remarks_file_x++;
			}
			if (isset($remarks_file_d)) { unset($remarks_file_d); }
			if (isset($remarks_file_x)) { unset($remarks_file_x); }
			if (isset($rkey)) { unset($rkey); }
			if (isset($patient_file_d)) { unset($patient_file_d); }
			if (isset($patient_file_x)) { unset($patient_file_x); }
			if (isset($patient_file_a)) { unset($patient_file_a); }
			if (isset($patient_file_b)) { unset($patient_file_b); }
		}

		//exam data
		$res_file_array = array();
		while (($res_filename_data = fgets($res_filename)) !== FALSE)
		{
			array_push($res_file_array, "$res_filename_data");
		}

		$res_file_array_numb = count($res_file_array);
		$res_file_array_x = 0;

		$DL_Xmm = 0;
		$DL_Ymm = 0;
		$DL_Zmm = 0;
		$DL_x = 0;
		$DR_Xmm = 0;
		$DR_Ymm = 0;
		$DR_Zmm = 0;
		$DR_x = 0;
		$VP_Xmm = 0;
		$VP_Ymm = 0;
		$VP_Zmm = 0;
		$VP_x = 0;
		$pt = "";
		$pt_last = "";
		$scantime = 0;
		$scantime_last = 0;
		$test = "";
		$test_last = "";
		$set_header = 0;
		$PlumbResult_array = array();
			$PlumbResult_array["PlumbResult_0101_TrunkLengthVPDM_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0102_TrunkLengthVPSP_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0103_TrunkLengthVPSP_percent"] = "NULL";
			$PlumbResult_array["PlumbResult_0104_DimpleDistanceDLDR_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0105_DimpleDistanceDLDR_percent"] = "NULL";
			$PlumbResult_array["PlumbResult_0201_TrunkInclinationVPDM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0202_TrunkInclinationVPDM_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0203_TrunkImbalanceVPDM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0204_TrunkImbalanceVPDM_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0206_PelvicTiltDLDR_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0207_PelvicTiltDLDR_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0208_PelvicTorsionDLDR_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0209_PelvicInclinationDimples_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0211_RotationCorrectionPelvis_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0301_InflectionPointICT_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0302_KyphoticApexKA_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0303_InflectionPointITL_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0304_LordoticApexLA_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0305_InflectionPointILS_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0306_FlecheCervicale_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0316_FlecheCervicaleVP_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0307_FlecheLombaire_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0401_KyphoticAngleICTITLmax_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0402_KyphoticAngleVPITL_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0403_KyphoticAngleVPT12_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0404_LordoticAngleITLILSmax_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0405_LordoticAngleITLDM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0406_LordoticAngleT12DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0407_PelvicInclinationSymmetryLine_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0408_SurfaceRotationRms_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0409_SurfaceRotationMax_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0411_SurfaceRotationPlusMax_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0412_SurfaceRotationMinusMax_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0413_SurfaceRotationAmplitude_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0414_TrunkTorsion_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_0501_LateralDeviationVPDMRms_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0502_LateralDeviationVPDMMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0503_LateralDeviationVPDMPlusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0504_LateralDeviationVPDMMinusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_0505_LateralDeviationVPDMAmplitude_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_8000_WeissIndex_rel"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L3"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_T12"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_T12"] = "NULL";
			$PlumbResult_array["PlumbResult_1411_SurfaceRotationPlusMaxVPDMPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_1412_SurfaceRotationMinusMaxVPDMPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_1503_LateralDeviationVPDMPlusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_1504_LateralDeviationVPDMMinusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2501_LateralDeviationSymmLineVPDMRms_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2502_LateralDeviationSymmLineVPDMMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2503_LateralDeviationSymmLineVPDMPlusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2504_LateralDeviationSymmLineVPDMMinusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2505_LateralDeviationSymmLineVPDMAmplitude_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2523_LateralDeviationSymmLineVPDMPlusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_2524_LateralDeviationSymmLineVPDMMinusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4101_TrunkLengthT4DM_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4408_SurfaceRotationRmsT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4409_SurfaceRotationMaxT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4411_SurfaceRotationPlusMaxT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4412_SurfaceRotationMinusMaxT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4413_SurfaceRotationAmplitudeT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4415_SurfaceRotationMeanT4DM_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_4421_SurfaceRotationPlusMaxT4DMPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4422_SurfaceRotationMinusMaxT4DMPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4501_LateralDeviationT4DMRms_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4502_LateralDeviationT4DMMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4503_LateralDeviationT4DMPlusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4504_LateralDeviationT4DMMinusMax_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4505_LateralDeviationT4DMAmplitude_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4515_LateralDeviationT4DMMean_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4523_LateralDeviationT4DMPlusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_4524_LateralDeviationT4DMMinusMaxPos_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_3201_TrunkInclinationICTITL_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_3202_TrunkInclinationICTITL_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_3203_TrunkInclinationITLILS_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_3204_TrunkInclinationITLILS_mm"] = "NULL";
			$PlumbResult_array["PlumbResult_8100_GrivasIndex_rel"] = "NULL";
			$PlumbResult_array["PlumbResult_3210_PelvicInclinationAngleDL_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_3211_PelvicInclinationAngleDR_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_3214_PelvicOpeningAngleDL_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_3215_PelvicOpeningAngleDL_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L1"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L2"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L4"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L1-L2"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L2-L3"] = "NULL";
			$PlumbResult_array["PlumbResult_8001_WeissLAPos_L3-L4"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_T12-L1"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L1"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L2"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L3"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L4"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L1-L2"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L2-L3"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_L3-L4"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_T11"] = "NULL";
			$PlumbResult_array["PlumbResult_8002_WeissITLPos_T11-T12"] = "NULL";
			$PlumbResult_array["PlumbResult_2206_PelvicDropDLDR_deg"] = "NULL";
			$PlumbResult_array["PlumbResult_2207_PelvicDropDLDR_mm"] = "NULL";
		$PlumbCount_array = array();
			$PlumbCount_array["PlumbResult_0101_TrunkLengthVPDM_mm"] = 0;
			$PlumbCount_array["PlumbResult_0102_TrunkLengthVPSP_mm"] = 0;
			$PlumbCount_array["PlumbResult_0103_TrunkLengthVPSP_percent"] = 0;
			$PlumbCount_array["PlumbResult_0104_DimpleDistanceDLDR_mm"] = 0;
			$PlumbCount_array["PlumbResult_0105_DimpleDistanceDLDR_percent"] = 0;
			$PlumbCount_array["PlumbResult_0201_TrunkInclinationVPDM_deg"] = 0;
			$PlumbCount_array["PlumbResult_0202_TrunkInclinationVPDM_mm"] = 0;
			$PlumbCount_array["PlumbResult_0203_TrunkImbalanceVPDM_deg"] = 0;
			$PlumbCount_array["PlumbResult_0204_TrunkImbalanceVPDM_mm"] = 0;
			$PlumbCount_array["PlumbResult_0206_PelvicTiltDLDR_deg"] = 0;
			$PlumbCount_array["PlumbResult_0207_PelvicTiltDLDR_mm"] = 0;
			$PlumbCount_array["PlumbResult_0208_PelvicTorsionDLDR_deg"] = 0;
			$PlumbCount_array["PlumbResult_0209_PelvicInclinationDimples_deg"] = 0;
			$PlumbCount_array["PlumbResult_0211_RotationCorrectionPelvis_deg"] = 0;
			$PlumbCount_array["PlumbResult_0301_InflectionPointICT_mm"] = 0;
			$PlumbCount_array["PlumbResult_0302_KyphoticApexKA_mm"] = 0;
			$PlumbCount_array["PlumbResult_0303_InflectionPointITL_mm"] = 0;
			$PlumbCount_array["PlumbResult_0304_LordoticApexLA_mm"] = 0;
			$PlumbCount_array["PlumbResult_0305_InflectionPointILS_mm"] = 0;
			$PlumbCount_array["PlumbResult_0306_FlecheCervicale_mm"] = 0;
			$PlumbCount_array["PlumbResult_0316_FlecheCervicaleVP_mm"] = 0;
			$PlumbCount_array["PlumbResult_0307_FlecheLombaire_mm"] = 0;
			$PlumbCount_array["PlumbResult_0401_KyphoticAngleICTITLmax_deg"] = 0;
			$PlumbCount_array["PlumbResult_0402_KyphoticAngleVPITL_deg"] = 0;
			$PlumbCount_array["PlumbResult_0403_KyphoticAngleVPT12_deg"] = 0;
			$PlumbCount_array["PlumbResult_0404_LordoticAngleITLILSmax_deg"] = 0;
			$PlumbCount_array["PlumbResult_0405_LordoticAngleITLDM_deg"] = 0;
			$PlumbCount_array["PlumbResult_0406_LordoticAngleT12DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_0407_PelvicInclinationSymmetryLine_deg"] = 0;
			$PlumbCount_array["PlumbResult_0408_SurfaceRotationRms_deg"] = 0;
			$PlumbCount_array["PlumbResult_0409_SurfaceRotationMax_deg"] = 0;
			$PlumbCount_array["PlumbResult_0411_SurfaceRotationPlusMax_deg"] = 0;
			$PlumbCount_array["PlumbResult_0412_SurfaceRotationMinusMax_deg"] = 0;
			$PlumbCount_array["PlumbResult_0413_SurfaceRotationAmplitude_deg"] = 0;
			$PlumbCount_array["PlumbResult_0414_TrunkTorsion_deg"] = 0;
			$PlumbCount_array["PlumbResult_0501_LateralDeviationVPDMRms_mm"] = 0;
			$PlumbCount_array["PlumbResult_0502_LateralDeviationVPDMMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_0503_LateralDeviationVPDMPlusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_0504_LateralDeviationVPDMMinusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_0505_LateralDeviationVPDMAmplitude_mm"] = 0;
			$PlumbCount_array["PlumbResult_8000_WeissIndex_rel"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L3"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_T12"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_T12"] = 0;
			$PlumbCount_array["PlumbResult_1411_SurfaceRotationPlusMaxVPDMPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_1412_SurfaceRotationMinusMaxVPDMPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_1503_LateralDeviationVPDMPlusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_1504_LateralDeviationVPDMMinusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_2501_LateralDeviationSymmLineVPDMRms_mm"] = 0;
			$PlumbCount_array["PlumbResult_2502_LateralDeviationSymmLineVPDMMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_2503_LateralDeviationSymmLineVPDMPlusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_2504_LateralDeviationSymmLineVPDMMinusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_2505_LateralDeviationSymmLineVPDMAmplitude_mm"] = 0;
			$PlumbCount_array["PlumbResult_2523_LateralDeviationSymmLineVPDMPlusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_2524_LateralDeviationSymmLineVPDMMinusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_4101_TrunkLengthT4DM_mm"] = 0;
			$PlumbCount_array["PlumbResult_4408_SurfaceRotationRmsT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4409_SurfaceRotationMaxT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4411_SurfaceRotationPlusMaxT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4412_SurfaceRotationMinusMaxT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4413_SurfaceRotationAmplitudeT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4415_SurfaceRotationMeanT4DM_deg"] = 0;
			$PlumbCount_array["PlumbResult_4421_SurfaceRotationPlusMaxT4DMPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_4422_SurfaceRotationMinusMaxT4DMPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_4501_LateralDeviationT4DMRms_mm"] = 0;
			$PlumbCount_array["PlumbResult_4502_LateralDeviationT4DMMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_4503_LateralDeviationT4DMPlusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_4504_LateralDeviationT4DMMinusMax_mm"] = 0;
			$PlumbCount_array["PlumbResult_4505_LateralDeviationT4DMAmplitude_mm"] = 0;
			$PlumbCount_array["PlumbResult_4515_LateralDeviationT4DMMean_mm"] = 0;
			$PlumbCount_array["PlumbResult_4523_LateralDeviationT4DMPlusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_4524_LateralDeviationT4DMMinusMaxPos_mm"] = 0;
			$PlumbCount_array["PlumbResult_3201_TrunkInclinationICTITL_deg"] = 0;
			$PlumbCount_array["PlumbResult_3202_TrunkInclinationICTITL_mm"] = 0;
			$PlumbCount_array["PlumbResult_3203_TrunkInclinationITLILS_deg"] = 0;
			$PlumbCount_array["PlumbResult_3204_TrunkInclinationITLILS_mm"] = 0;
			$PlumbCount_array["PlumbResult_8100_GrivasIndex_rel"] = 0;
			$PlumbCount_array["PlumbResult_3210_PelvicInclinationAngleDL_deg"] = 0;
			$PlumbCount_array["PlumbResult_3211_PelvicInclinationAngleDR_deg"] = 0;
			$PlumbCount_array["PlumbResult_3214_PelvicOpeningAngleDL_deg"] = 0;
			$PlumbCount_array["PlumbResult_3215_PelvicOpeningAngleDL_deg"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L1"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L2"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L4"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L1-L2"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L2-L3"] = 0;
			$PlumbCount_array["PlumbResult_8001_WeissLAPos_L3-L4"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_T12-L1"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L1"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L2"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L3"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L4"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L1-L2"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L2-L3"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_L3-L4"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_T11"] = 0;
			$PlumbCount_array["PlumbResult_8002_WeissITLPos_T11-T12"] = 0;
			$PlumbCount_array["PlumbResult_2206_PelvicDropDLDR_deg"] = 0;
			$PlumbCount_array["PlumbResult_2207_PelvicDropDLDR_mm"] = 0;
		$remarks = "NULL";

		while ($res_file_array_x < $res_file_array_numb)
		{
			$res_file = $res_file_array[$res_file_array_x];
			logger(__LINE__, "array-> $res_file_array_x of $res_file_array_numb = $res_file");
			$res_file = trim($res_file);
			$res_ini_filename = fopen("$res_file","r") or die;

			while (($res_data = fgetss($res_ini_filename)) !== FALSE)
				{
					$res_data = preg_replace('/\s\s+/', ' ', $res_data);
					$res_data = trim($res_data);
					$res_data = explode(" ", $res_data);

					if (trim($res_data[0]) == "Frame")
						{
							//capture Pt. name, Scan Day and Scan number.
							$pt_last = $pt;
							$folder_data = explode('\\', $res_file);
							$pt = $patient_file_array[substr($folder_data[7], 0, 17)]["created"];

							$scantime_last = $scantime;
							$scan_data = explode('_', $folder_data[7]);
							$scantime = substr($scan_data[0], 8, 8);

							$baseline_flag =  $folder_data[7];

							$test_last = $test;
							$test = substr($scan_data[0], 0, 8);
							$day = $test;

							// Capture Remarks
							$remarks = $remarks_file_array[substr($folder_data[7], 0, 17)];
							if (strlen($remarks) < 1) { $remarks = "NULL"; }

							if ($scantime_last == 0)
								{
									$scantime_last = $scantime;
									$day_last = $day;
									$baseline_flag_last = $baseline_flag;
								}

							//The scantime changes when we change scandatasets, so do maths and reset before going forward.
							if ($scantime_last != $scantime)
								{
									logger(__LINE__, "Calculating averages: " . number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
									//XYZ averages
									$DL_Xmm = ($DL_Xmm / $DL_x);
									$DL_Ymm = ($DL_Ymm / $DL_x);
									$DL_Zmm = ($DL_Zmm / $DL_x);
									$DR_Xmm = ($DR_Xmm / $DR_x);
									$DR_Ymm = ($DR_Ymm / $DR_x);
									$DR_Zmm = ($DR_Zmm / $DR_x);
									$VP_Xmm = ($VP_Xmm / $VP_x);
									$VP_Ymm = ($VP_Ymm / $VP_x);
									$VP_Zmm = ($VP_Zmm / $VP_x);

									//measure distance
									$DL_DR = sqrt(pow(($DL_Xmm - $DR_Xmm) ,2) + pow(($DL_Ymm - $DR_Ymm), 2) + pow(($DL_Zmm - $DR_Zmm), 2));
									$VP_DL = sqrt(pow(($VP_Xmm - $DL_Xmm) ,2) + pow(($VP_Ymm - $DL_Ymm), 2) + pow(($VP_Zmm - $DL_Zmm), 2));
									$VP_DR = sqrt(pow(($VP_Xmm - $DR_Xmm) ,2) + pow(($VP_Ymm - $DR_Ymm), 2) + pow(($VP_Zmm - $DR_Zmm), 2));

									//Motion vs No_motion
									if ((strpos($test_last, "Part") > 0) || (strpos($baseline_flag_last, "Dynamic") > 0))
										{
											$motion = "With Motion";
										}
										else
										{
											$motion = "No Motion";
										}

									//data output
									//Write CSV header data on first pass.
									if ($set_header == 0)
										{
											logger(__LINE__, "Write CSV header on first pass: " . number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");

											fwrite($output_filename, "pt,remarks,source,day,scantime,Motion?,DL-DR,VP-DL,VP-DR,DL_Xmm,DL_Ymm,DL_Zmm,DR_Xmm,DR_Ymm,DR_Zmm,VP_Xmm,VP_Ymm,VP_Zmm");
											ksort($PlumbResult_array);
											reset($PlumbResult_array);
											while(list($Plumb_name, $Plumb_value) = each($PlumbResult_array))
												{
													fwrite($output_filename, "," . $Plumb_name);
												}
											fwrite($output_filename, "\r\n");
											$set_header++;
										}

									//notify user of progress
									logger(__LINE__, "Now on file ($res_file_array_x) of $res_file_array_numb");
									logger(__LINE__, "file -> $pt_last, $day, $scantime_last");
									logger(__LINE__, number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
									logger(__LINE__, "Writing output -> " . $pt_last . "," . $baseline_flag_last . "," . $test_last . "," . $scantime_last . "," . $motion . "," . $DL_DR . "," . $VP_DL . "," . $VP_DR . "," . $DL_Xmm .",". $DL_Ymm .",". $DL_Zmm  .",". $DR_Xmm .",". $DR_Ymm .",". $DR_Zmm .",". $VP_Xmm .",". $VP_Ymm .",". $VP_Zmm);

									fwrite($output_filename, "". $pt_last . "," . $remarks . "," . $baseline_flag_last . "," . $test_last . "," . $scantime_last . "," . $motion . "," . $DL_DR . "," . $VP_DL . "," . $VP_DR . "," . $DL_Xmm .",". $DL_Ymm .",". $DL_Zmm  .",". $DR_Xmm .",". $DR_Ymm .",". $DR_Zmm .",". $VP_Xmm .",". $VP_Ymm .",". $VP_Zmm);
									ksort($PlumbResult_array);
									reset($PlumbResult_array);
									while(list($Plumb_name, $Plumb_value) = each($PlumbResult_array))
										{
											//Plumb Averages
											if ($Plumb_value !== "NULL")
												{
													$Plumb_avg = $Plumb_value / $PlumbCount_array[$Plumb_name];
												}
												else
												{
													$Plumb_avg = "NULL";
												}

											fwrite($output_filename, "," . $Plumb_avg);
										}

									fwrite($output_filename, "\r\n");
									$DL_Xmm = 0;
									$DL_Ymm = 0;
									$DL_Zmm = 0;
									$DL_x = 0;
									$DR_Xmm = 0;
									$DR_Ymm = 0;
									$DR_Zmm = 0;
									$DR_x = 0;
									$VP_Xmm = 0;
									$VP_Ymm = 0;
									$VP_Zmm = 0;
									$VP_x = 0;
									$PlumbResult_array = array();
									$PlumbResult_array["PlumbResult_0101_TrunkLengthVPDM_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0102_TrunkLengthVPSP_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0103_TrunkLengthVPSP_percent"] = "NULL";
									$PlumbResult_array["PlumbResult_0104_DimpleDistanceDLDR_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0105_DimpleDistanceDLDR_percent"] = "NULL";
									$PlumbResult_array["PlumbResult_0201_TrunkInclinationVPDM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0202_TrunkInclinationVPDM_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0203_TrunkImbalanceVPDM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0204_TrunkImbalanceVPDM_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0206_PelvicTiltDLDR_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0207_PelvicTiltDLDR_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0208_PelvicTorsionDLDR_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0209_PelvicInclinationDimples_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0211_RotationCorrectionPelvis_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0301_InflectionPointICT_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0302_KyphoticApexKA_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0303_InflectionPointITL_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0304_LordoticApexLA_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0305_InflectionPointILS_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0306_FlecheCervicale_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0316_FlecheCervicaleVP_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0307_FlecheLombaire_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0401_KyphoticAngleICTITLmax_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0402_KyphoticAngleVPITL_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0403_KyphoticAngleVPT12_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0404_LordoticAngleITLILSmax_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0405_LordoticAngleITLDM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0406_LordoticAngleT12DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0407_PelvicInclinationSymmetryLine_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0408_SurfaceRotationRms_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0409_SurfaceRotationMax_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0411_SurfaceRotationPlusMax_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0412_SurfaceRotationMinusMax_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0413_SurfaceRotationAmplitude_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0414_TrunkTorsion_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_0501_LateralDeviationVPDMRms_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0502_LateralDeviationVPDMMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0503_LateralDeviationVPDMPlusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0504_LateralDeviationVPDMMinusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_0505_LateralDeviationVPDMAmplitude_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_8000_WeissIndex_rel"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L3"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_T12"] = "NULL";
									$PlumbResult_array["PlumbResult_1411_SurfaceRotationPlusMaxVPDMPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_1412_SurfaceRotationMinusMaxVPDMPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_1503_LateralDeviationVPDMPlusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_1504_LateralDeviationVPDMMinusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2501_LateralDeviationSymmLineVPDMRms_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2502_LateralDeviationSymmLineVPDMMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2503_LateralDeviationSymmLineVPDMPlusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2504_LateralDeviationSymmLineVPDMMinusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2505_LateralDeviationSymmLineVPDMAmplitude_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2523_LateralDeviationSymmLineVPDMPlusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_2524_LateralDeviationSymmLineVPDMMinusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4101_TrunkLengthT4DM_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4408_SurfaceRotationRmsT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4409_SurfaceRotationMaxT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4411_SurfaceRotationPlusMaxT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4412_SurfaceRotationMinusMaxT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4413_SurfaceRotationAmplitudeT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4415_SurfaceRotationMeanT4DM_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_4421_SurfaceRotationPlusMaxT4DMPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4422_SurfaceRotationMinusMaxT4DMPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4501_LateralDeviationT4DMRms_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4502_LateralDeviationT4DMMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4503_LateralDeviationT4DMPlusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4504_LateralDeviationT4DMMinusMax_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4505_LateralDeviationT4DMAmplitude_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4515_LateralDeviationT4DMMean_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4523_LateralDeviationT4DMPlusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_4524_LateralDeviationT4DMMinusMaxPos_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_3201_TrunkInclinationICTITL_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_3202_TrunkInclinationICTITL_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_3203_TrunkInclinationITLILS_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_3204_TrunkInclinationITLILS_mm"] = "NULL";
									$PlumbResult_array["PlumbResult_8100_GrivasIndex_rel"] = "NULL";
									$PlumbResult_array["PlumbResult_3210_PelvicInclinationAngleDL_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_3211_PelvicInclinationAngleDR_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_3214_PelvicOpeningAngleDL_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_3215_PelvicOpeningAngleDL_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L1"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L2"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L4"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L1-L2"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L2-L3"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_L3-L4"] = "NULL";
									$PlumbResult_array["PlumbResult_8001_WeissLAPos_T12"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_T12-L1"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L1"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L2"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L3"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L4"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L1-L2"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L2-L3"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_L3-L4"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_T11"] = "NULL";
									$PlumbResult_array["PlumbResult_8002_WeissITLPos_T11-T12"] = "NULL";
									$PlumbResult_array["PlumbResult_2206_PelvicDropDLDR_deg"] = "NULL";
									$PlumbResult_array["PlumbResult_2207_PelvicDropDLDR_mm"] = "NULL";
									$PlumbCount_array = array();
									$PlumbCount_array["PlumbResult_0101_TrunkLengthVPDM_mm"] = 0;
									$PlumbCount_array["PlumbResult_0102_TrunkLengthVPSP_mm"] = 0;
									$PlumbCount_array["PlumbResult_0103_TrunkLengthVPSP_percent"] = 0;
									$PlumbCount_array["PlumbResult_0104_DimpleDistanceDLDR_mm"] = 0;
									$PlumbCount_array["PlumbResult_0105_DimpleDistanceDLDR_percent"] = 0;
									$PlumbCount_array["PlumbResult_0201_TrunkInclinationVPDM_deg"] = 0;
									$PlumbCount_array["PlumbResult_0202_TrunkInclinationVPDM_mm"] = 0;
									$PlumbCount_array["PlumbResult_0203_TrunkImbalanceVPDM_deg"] = 0;
									$PlumbCount_array["PlumbResult_0204_TrunkImbalanceVPDM_mm"] = 0;
									$PlumbCount_array["PlumbResult_0206_PelvicTiltDLDR_deg"] = 0;
									$PlumbCount_array["PlumbResult_0207_PelvicTiltDLDR_mm"] = 0;
									$PlumbCount_array["PlumbResult_0208_PelvicTorsionDLDR_deg"] = 0;
									$PlumbCount_array["PlumbResult_0209_PelvicInclinationDimples_deg"] = 0;
									$PlumbCount_array["PlumbResult_0211_RotationCorrectionPelvis_deg"] = 0;
									$PlumbCount_array["PlumbResult_0301_InflectionPointICT_mm"] = 0;
									$PlumbCount_array["PlumbResult_0302_KyphoticApexKA_mm"] = 0;
									$PlumbCount_array["PlumbResult_0303_InflectionPointITL_mm"] = 0;
									$PlumbCount_array["PlumbResult_0304_LordoticApexLA_mm"] = 0;
									$PlumbCount_array["PlumbResult_0305_InflectionPointILS_mm"] = 0;
									$PlumbCount_array["PlumbResult_0306_FlecheCervicale_mm"] = 0;
									$PlumbCount_array["PlumbResult_0316_FlecheCervicaleVP_mm"] = 0;
									$PlumbCount_array["PlumbResult_0307_FlecheLombaire_mm"] = 0;
									$PlumbCount_array["PlumbResult_0401_KyphoticAngleICTITLmax_deg"] = 0;
									$PlumbCount_array["PlumbResult_0402_KyphoticAngleVPITL_deg"] = 0;
									$PlumbCount_array["PlumbResult_0403_KyphoticAngleVPT12_deg"] = 0;
									$PlumbCount_array["PlumbResult_0404_LordoticAngleITLILSmax_deg"] = 0;
									$PlumbCount_array["PlumbResult_0405_LordoticAngleITLDM_deg"] = 0;
									$PlumbCount_array["PlumbResult_0406_LordoticAngleT12DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_0407_PelvicInclinationSymmetryLine_deg"] = 0;
									$PlumbCount_array["PlumbResult_0408_SurfaceRotationRms_deg"] = 0;
									$PlumbCount_array["PlumbResult_0409_SurfaceRotationMax_deg"] = 0;
									$PlumbCount_array["PlumbResult_0411_SurfaceRotationPlusMax_deg"] = 0;
									$PlumbCount_array["PlumbResult_0412_SurfaceRotationMinusMax_deg"] = 0;
									$PlumbCount_array["PlumbResult_0413_SurfaceRotationAmplitude_deg"] = 0;
									$PlumbCount_array["PlumbResult_0414_TrunkTorsion_deg"] = 0;
									$PlumbCount_array["PlumbResult_0501_LateralDeviationVPDMRms_mm"] = 0;
									$PlumbCount_array["PlumbResult_0502_LateralDeviationVPDMMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_0503_LateralDeviationVPDMPlusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_0504_LateralDeviationVPDMMinusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_0505_LateralDeviationVPDMAmplitude_mm"] = 0;
									$PlumbCount_array["PlumbResult_8000_WeissIndex_rel"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L3"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_T12"] = 0;
									$PlumbCount_array["PlumbResult_1411_SurfaceRotationPlusMaxVPDMPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_1412_SurfaceRotationMinusMaxVPDMPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_1503_LateralDeviationVPDMPlusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_1504_LateralDeviationVPDMMinusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_2501_LateralDeviationSymmLineVPDMRms_mm"] = 0;
									$PlumbCount_array["PlumbResult_2502_LateralDeviationSymmLineVPDMMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_2503_LateralDeviationSymmLineVPDMPlusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_2504_LateralDeviationSymmLineVPDMMinusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_2505_LateralDeviationSymmLineVPDMAmplitude_mm"] = 0;
									$PlumbCount_array["PlumbResult_2523_LateralDeviationSymmLineVPDMPlusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_2524_LateralDeviationSymmLineVPDMMinusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_4101_TrunkLengthT4DM_mm"] = 0;
									$PlumbCount_array["PlumbResult_4408_SurfaceRotationRmsT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4409_SurfaceRotationMaxT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4411_SurfaceRotationPlusMaxT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4412_SurfaceRotationMinusMaxT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4413_SurfaceRotationAmplitudeT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4415_SurfaceRotationMeanT4DM_deg"] = 0;
									$PlumbCount_array["PlumbResult_4421_SurfaceRotationPlusMaxT4DMPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_4422_SurfaceRotationMinusMaxT4DMPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_4501_LateralDeviationT4DMRms_mm"] = 0;
									$PlumbCount_array["PlumbResult_4502_LateralDeviationT4DMMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_4503_LateralDeviationT4DMPlusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_4504_LateralDeviationT4DMMinusMax_mm"] = 0;
									$PlumbCount_array["PlumbResult_4505_LateralDeviationT4DMAmplitude_mm"] = 0;
									$PlumbCount_array["PlumbResult_4515_LateralDeviationT4DMMean_mm"] = 0;
									$PlumbCount_array["PlumbResult_4523_LateralDeviationT4DMPlusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_4524_LateralDeviationT4DMMinusMaxPos_mm"] = 0;
									$PlumbCount_array["PlumbResult_3201_TrunkInclinationICTITL_deg"] = 0;
									$PlumbCount_array["PlumbResult_3202_TrunkInclinationICTITL_mm"] = 0;
									$PlumbCount_array["PlumbResult_3203_TrunkInclinationITLILS_deg"] = 0;
									$PlumbCount_array["PlumbResult_3204_TrunkInclinationITLILS_mm"] = 0;
									$PlumbCount_array["PlumbResult_8100_GrivasIndex_rel"] = 0;
									$PlumbCount_array["PlumbResult_3210_PelvicInclinationAngleDL_deg"] = 0;
									$PlumbCount_array["PlumbResult_3211_PelvicInclinationAngleDR_deg"] = 0;
									$PlumbCount_array["PlumbResult_3214_PelvicOpeningAngleDL_deg"] = 0;
									$PlumbCount_array["PlumbResult_3215_PelvicOpeningAngleDL_deg"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L1"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L2"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L4"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L1-L2"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L2-L3"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_L3-L4"] = 0;
									$PlumbCount_array["PlumbResult_8001_WeissLAPos_T12"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_T12-L1"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L1"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L2"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L3"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L4"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L1-L2"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L2-L3"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_L3-L4"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_T11"] = 0;
									$PlumbCount_array["PlumbResult_8002_WeissITLPos_T11-T12"] = 0;
									$PlumbCount_array["PlumbResult_2206_PelvicDropDLDR_deg"] = 0;
									$PlumbCount_array["PlumbResult_2207_PelvicDropDLDR_mm"] = 0;
								}
						}

					if (trim($res_data[0]) == "Fixpoint_DL")
						{
							$DL_Xmm = $DL_Xmm + (trim($res_data[3]) * .1);
							$DL_Ymm = $DL_Ymm + (trim($res_data[4]) * .1);
							$DL_Zmm = $DL_Zmm + (trim($res_data[5]) * .1);
							$DL_x++;
							logger(__LINE__, "Fixpoint_DL-> X=$DL_Xmm, Y=$DL_Ymm, Z=$DL_Zmm");
						}

					if (trim($res_data[0]) == "Fixpoint_DR")
						{
							$DR_Xmm = $DR_Xmm + (trim($res_data[3]) * .1);
							$DR_Ymm = $DR_Ymm + (trim($res_data[4]) * .1);
							$DR_Zmm = $DR_Zmm + (trim($res_data[5]) * .1);
							$DR_x++;
							logger(__LINE__, "Fixpoint_DR-> X=$DR_Xmm, Y=$DR_Ymm, Z=$DR_Zmm");
						}

					if (trim($res_data[0]) == "Fixpoint_VP")
						{
							$VP_Xmm = $VP_Xmm + (trim($res_data[3]) * .1);
							$VP_Ymm = $VP_Ymm + (trim($res_data[4]) * .1);
							$VP_Zmm = $VP_Zmm + (trim($res_data[5]) * .1);
							$VP_x++;
							logger(__LINE__, "Fixpoint_VP-> X=$VP_Xmm, Y=$VP_Ymm, Z=$VP_Zmm");
						}

					if (substr(trim($res_data[0]), 0, 11) == "PlumbResult")
						{
							if (isset($PlumbResult_array[$res_data[0]]))
								{
									$PlumbResult_newvalue = $PlumbResult_array[trim($res_data[0])] + (trim($res_data[1]) * .1);
									$PlumbResult_array[trim($res_data[0])] = $PlumbResult_newvalue;
									$PlumbCount_array[trim($res_data[0])]++;
								}
							else
								{
									$PlumbResult_array[trim($res_data[0])] = (trim($res_data[1]) * .1);
									$PlumbCount_array[trim($res_data[0])]++;
								}
						}
				}

			fclose($res_ini_filename);
			$res_file_array_x++;
			logger(__LINE__, "End of loop: " . number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
		}

		//save the last fileset
			if ($res_file_array_x = $res_file_array_numb)
				{
					logger(__LINE__, "last file-> $pt_last, $day_last, $scantime_last");

					//XYZ averages
					$DL_Xmm = ($DL_Xmm / $DL_x);
					$DL_Ymm = ($DL_Ymm / $DL_x);
					$DL_Zmm = ($DL_Zmm / $DL_x);
					$DR_Xmm = ($DR_Xmm / $DR_x);
					$DR_Ymm = ($DR_Ymm / $DR_x);
					$DR_Zmm = ($DR_Zmm / $DR_x);
					$VP_Xmm = ($VP_Xmm / $VP_x);
					$VP_Ymm = ($VP_Ymm / $VP_x);
					$VP_Zmm = ($VP_Zmm / $VP_x);

					//measure distance
					$DL_DR = sqrt(pow(($DL_Xmm - $DR_Xmm) ,2) + pow(($DL_Ymm - $DR_Ymm), 2) + pow(($DL_Zmm - $DR_Zmm), 2));
					$VP_DL = sqrt(pow(($VP_Xmm - $DL_Xmm) ,2) + pow(($VP_Ymm - $DL_Ymm), 2) + pow(($VP_Zmm - $DL_Zmm), 2));
					$VP_DR = sqrt(pow(($VP_Xmm - $DR_Xmm) ,2) + pow(($VP_Ymm - $DR_Ymm), 2) + pow(($VP_Zmm - $DR_Zmm), 2));

					//Motion vs No_motion
					if ((strpos($test_last, "Part") > 0) || (strpos($baseline_flag_last, "Dynamic") > 0))
						{
							$motion = "With Motion";
						}
						else
						{
							$motion = "No Motion";
						}

					//data output
					//Write CSV header data on first pass.
					logger(__LINE__, number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
					if ($set_header == 0)
						{
							logger(__LINE__, "Write CSV header on first pass: " . number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
							fwrite($output_filename, "pt,source,day,scantime,Motion?,DL-DR,VP-DL,VP-DR,DL_Xmm,DL_Ymm,DL_Zmm,DR_Xmm,DR_Ymm,DR_Zmm,VP_Xmm,VP_Ymm,VP_Zmm");
							ksort($PlumbResult_array);
							reset($PlumbResult_array);
							while(list($Plumb_name, $Plumb_value) = each($PlumbResult_array))
								{
									fwrite($output_filename, "," . $Plumb_name);
								}
							fwrite($output_filename, "\r\n");
							$set_header++;
						}

					//notify user of progress
					logger(__LINE__, "Now on file ($res_file_array_x) of $res_file_array_numb");
					logger(__LINE__, number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
					logger(__LINE__, "Writing output -> " . $pt_last . "," . $baseline_flag_last . "," . $test_last . "," . $scantime_last . "," . $motion . "," . $DL_DR . "," . $VP_DL . "," . $VP_DR . "," . $DL_Xmm .",". $DL_Ymm .",". $DL_Zmm  .",". $DR_Xmm .",". $DR_Ymm .",". $DR_Zmm .",". $VP_Xmm .",". $VP_Ymm .",". $VP_Zmm);

					fwrite($output_filename, "". $pt_last . "," . $baseline_flag_last . "," . $test_last . "," . $scantime_last . "," . $motion . "," . $DL_DR . "," . $VP_DL . "," . $VP_DR . "," . $DL_Xmm .",". $DL_Ymm .",". $DL_Zmm  .",". $DR_Xmm .",". $DR_Ymm .",". $DR_Zmm .",". $VP_Xmm .",". $VP_Ymm .",". $VP_Zmm);
					ksort($PlumbResult_array);
					reset($PlumbResult_array);
					while(list($Plumb_name, $Plumb_value) = each($PlumbResult_array))
						{
							//Plumb Averages
							if ($Plumb_value !== "NULL")
								{
									$Plumb_avg = $Plumb_value / $PlumbCount_array[$Plumb_name];
								}
								else
								{
									$Plumb_avg = "NULL";
								}

							fwrite($output_filename, "," . $Plumb_avg);
						}
					fwrite($output_filename, "\r\n");
				}
	}

//all done with these - close.
fclose($res_filename);
fclose($output_filename);
logger(__LINE__, number_format((memory_get_usage() - $start_memory)) . " Bytes in use.");
logger(__LINE__, "===== End of Log. =====");
?>
